#!/bin/bash
set -e

user=user
uid=$(id -u)
gid=1000
jawk_download_url=https://sourceforge.net/projects/jawk/files/jawk/1.02/jawk.1_02.jar/download
pawk_download_url=http://www.math.utah.edu/pub/pawk/pawk-20030606.tar.gz
wak_download_url=https://github.com/raygard/wak/archive/refs/tags/v24.10.tar.gz
goawk_repo=github.com/benhoyt/goawk@latest

docker build . -t "${1:-awkbox}" -f - << __Dockerfile__
FROM debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y sudo make build-essential yacc bison maven curl git \
                                 original-awk mawk gawk bioawk busybox golang 9base \
                                 vim emacs
ENV LC_ALL=C.UTF-8
ARG USERNAME=${user}
ARG UID=${uid}
ARG GID=${gid}
RUN groupadd -g ${gid} ${user} && \
    useradd -m -u ${uid} -g ${gid} -s /bin/bash ${user} && \
    echo "${user} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN echo "${user}:changeme" | chpasswd

USER ${user}
WORKDIR /home/${user}

RUN mkdir bin
ENV PATH=/home/${user}/bin:\$PATH

# busybox
RUN mkdir -p busybox/bin && \
    ln -s /bin/busybox busybox/bin/awk
ENV PATH=/home/${user}/busybox/bin:\$PATH

# goawk
RUN go install ${goawk_repo}
ENV PATH=/home/${user}/go/bin:\$PATH

# pawk
COPY patches patches
RUN curl -sL ${pawk_download_url} | tar xvz && \
    cd pawk-20030606 && \
    patch -p0 < ../patches/pawk.patch && \
    make PROFILE="-DPROFILE -DHAVE_STDLIB_H -DHAVE_UNISTD_H -DMAXPROFILE=65535 -DLINENO_T=int" && \
    mkdir bin && \
    cp -p a.out /home/${user}/bin/pawk

# onetrueawk
RUN git clone --depth=1 https://github.com/onetrueawk/awk onetrueawk && \
    make -C onetrueawk && \
    cp -p onetrueawk/a.out /home/${user}/bin/onetrueawk

# 9base awk
RUN ln -s /usr/lib/plan9/bin/awk bin/awk-9base

# plan9port
RUN git clone --depth=1 https://github.com/9fans/plan9port
RUN echo 'WSYSTYPE=nowsys' >> plan9port/LOCAL.config
RUN cd plan9port && ./INSTALL
RUN ln -s /home/${user}/plan9port/bin/awk bin/awk-plan9port
ENV PATH=/home/${user}/bin:\$PATH

# wak
RUN curl -sL ${wak_download_url} | tar xvz && \
        cd wak-24.10 && \
        make && \
        sudo make install

# original jawk
RUN mkdir -p jawk/bin jawk/share
RUN curl -sL "${jawk_download_url}" > jawk/share/jawk-1.02.jar
COPY <<-__jawk__ bin/jawk-1.02
#!/bin/sh
LC_CTYPE=en_US.ISO8859-1 java \\\\
    -Dfile.encoding=latin1 \\\\
    -cp /home/${user}/jawk/share/jawk-1.02.jar \\\\
    org.jawk.Awk "\\\${@}" | cat
__jawk__
RUN sudo chown user:user bin/jawk-1.02 && \
        chmod +x bin/jawk-1.02

# hoijui's jawk
RUN git clone --depth=1 https://github.com/hoijui/Jawk hoijui-jawk && \
    cd hoijui-jawk && \
    patch -p1 < ../patches/hoijui-jawk.patch && \
    mvn package || true
COPY <<-__jawk__ bin/jawk-1.03
#!/bin/sh
LC_CTYPE=en_US.ISO8859-1 java \\\\
    -Dfile.encoding=latin1 \\\\
    -cp /home/${user}/hoijui-jawk/target/jawk-1.03-SNAPSHOT-stand-alone.jar \\\\
    org.jawk.Main "\\\${@}" | cat
__jawk__
RUN sudo chown user:user bin/jawk-1.03 && \
        chmod +x bin/jawk-1.03


RUN mkdir work
WORKDIR /home/${user}/work

CMD ["/bin/bash"]
__Dockerfile__

# vim: set et ts=4 sw=0 sts=-1:
