#!/bin/bash

cd "$(dirname "${0}")"/.. && {
    AWK=gawk AWKOPT=-d/dev/stdout \
    ./hsvba ./testdata/mso/word_office2007-12.0.6762.5000_dotm_ja-jp_001.dotm |
    grep ^_[^_] -c | xargs test 0 =
}

# vim: set et ts=4 sw=0 sts=-1:
